[project]
name = "7-laba"
version = "0.1.0"
description = ""
authors = [
    {name = "orest7702",email = "omykhailiv2023@itcollege.lviv.ua"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk (>=2.1.0,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
